---
apiVersion: v1
kind: Service
metadata:
  name: weather-nodeport
spec:
  selector:
    app: weather
  ports:
    - protocol: TCP
      port: {{.Values.weatherApp.port}}
      targetPort: 5000
  type: NodePort
